/*
 * This source file was generated by the Gradle 'init' task
 */
package trainsimulation;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

public class App extends JFrame {
public void createAndShowGUI() {
    this.setSize(1000, 700);
    this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    // add components and stuff
    this.setVisible(true);
}

    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                App app = new App();
                app.createAndShowGUI();
            }
        });
    }
}
